development:
  environment: "homologation"
  merchant_id: "{540BA6EE-39D7-3DC1-D87D-7F82C49A3598}"
  crypto_url: "http://localhost:9292"
  crypto_key: "1234561246"

test:
  environment: "homologation"
  merchant_id: "{540BA6EE-39D7-3DC1-D87D-7F82C49A3598}"
  crypto_url: "http://localhost:9292"
  crypto_key: "1234561246"

production:
  environment: "production"
  merchant_id: "{YOUR_MERCHANT_ID_ON_BRASPAG}"
  crypto_url: "http://localhost:9292"
  crypto_key: "1234561246"
