default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: olook
  password: olook
  host: localhost

development:
  <<: *default
  database: olook_braspag_development

test:
  <<: *default
  database: olook_braspag_test